### ISSUE TITLE
I cannot authenticate

### ISSUE THREAD

**Issue by bakhtyarkf** [Microsoft/vsts-dotnet-samples#119]
I used the sample code ,
I tried many other version including

new VssCredentials(new WindowsCredential(new NetworkCredential("user", "pass")))
new VssCredentials(true)
...

an i'm getting :
Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access.
Client authentication required.

`
using System;
using Microsoft.VisualStudio.Services.Client;
using Microsoft.VisualStudio.Services.WebApi;
using Microsoft.TeamFoundation.Core.WebApi;
using System.Collections.Generic;

namespace DualSupportClientSample
{
    class Program
    {
        internal const string vstsOrTfsCollectionUrl = "https://myaccname.visualstudio.com"; 

        public static void Main(string[] args)
        {
            try
            {
                VssConnection connection = new VssConnection(new Uri(vstsOrTfsCollectionUrl), new VssClientCredentials());

                ProjectHttpClient projectClient = connection.GetClient<ProjectHttpClient>();
                IEnumerable<TeamProjectReference> projects = projectClient.GetProjects().Result;
                foreach (TeamProjectReference p in projects)
                {
                    Console.WriteLine(p.Name);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0}: {1}", ex.GetType(), ex.Message);
            }
        }
    }
}
`

**Comment by justmarks** [comment]
What issue are you seeing when you use the sample code as written?  I just tried it using an MSA and an AAD backed account and both worked as expected - sign in dialog popped up and after entering the credentials for a user in the account the list of projects was displayed.

Why are you trying to use VssCredentials by passing a username and password?  That's not a supported option.  If you want to pass the username/password through code instead of being entered through the UI, you should take a look at the NonInteractive sample - https://github.com/Microsoft/vsts-auth-samples/tree/master/NonInteractivePatGenerationSample
